CREATE TABLE PPROYECCIO(
ID_FUNCION INT IDENTITY (1,1) NOT NULL,
FN_HORARIO SMALLDATETIME NOT NULL,
ID_SALA INT NOT NULL,
ID_PELICULA INT NOT NULL
CONSTRAINT [PK_PROYECCION] PRIMARY KEY CLUSTERED
([ID_FUNCION]ASC)ON[PRIMARY]
);
CREATE TABLE ASIENTO(
ID_ASIENTO INT IDENTITY (1,1) NOT NULL,
AS_ASIENTOS NVARCHAR(20)NOT NULL,
AS_DISPONIBLE BIT NOT NULL,
ID_SALA INT NOT NULL
CONSTRAINT [PK_ASIENTO] PRIMARY KEY CLUSTERED
([ID_ASIENTO]ASC)ON[PRIMARY]
);