USE [CINE]
GO
SET IDENTITY_INSERT [dbo].[ASIENTO] ON 

GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (1, N'AS1', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (2, N'AS2', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (3, N'AS3', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (4, N'AS4', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (5, N'AS5', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (6, N'AS6', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (7, N'AS7', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (8, N'AS8', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (9, N'AS9', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (10, N'AS10', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (11, N'AS11', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (12, N'AS12', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (13, N'AS13', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (14, N'AS14', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (15, N'AS15', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (16, N'AS16', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (17, N'AS17', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (18, N'AS18', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (19, N'AS19', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (20, N'AS20', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (21, N'AS21', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (22, N'AS22', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (23, N'AS23', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (24, N'AS24', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (25, N'AS25', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (26, N'AS26', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (27, N'AS27', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (28, N'AS28', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (29, N'AS29', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (30, N'AS30', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (31, N'AS31', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (32, N'AS32', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (33, N'AS33', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (34, N'AS34', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (35, N'AS35', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (36, N'AS36', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (37, N'AS37', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (38, N'AS38', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (39, N'AS39', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (40, N'AS40', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (41, N'AS41', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (42, N'AS42', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (43, N'AS43', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (44, N'AS44', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (45, N'AS45', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (46, N'AS46', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (47, N'AS47', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (48, N'AS48', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (49, N'AS49', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (50, N'AS50', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (51, N'AS51', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (52, N'AS52', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (53, N'AS53', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (54, N'AS54', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (55, N'AS55', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (56, N'AS56', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (57, N'AS57', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (58, N'AS58', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (59, N'AS59', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (60, N'AS60', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (61, N'AS61', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (62, N'AS62', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (63, N'AS63', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (64, N'AS64', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (65, N'AS65', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (66, N'AS66', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (67, N'AS67', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (68, N'AS68', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (69, N'AS69', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (70, N'AS70', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (71, N'AS71', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (72, N'AS72', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (73, N'AS73', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (74, N'AS74', 1)
GO
INSERT [dbo].[ASIENTO] ([ID_ASIENTO], [AS_ASIENTOS], [AS_DISPONIBLE]) VALUES (75, N'AS75', 1)
GO
SET IDENTITY_INSERT [dbo].[ASIENTO] OFF
GO
